### ISSUE TITLE
echo: write error: Invalid argument /sys/class/dewb/add_mirrors

### ISSUE THREAD

**Issue by tmnkey** [scality/RestBlockDriver#34]
To write into /sys/class/dewb/add_mirrors, we need to call "echo" command twice to make it successful. 
As is below: 
.......
root@app05:/nfs/test/packages/RestBlockDriver# sudo -s
root@app05:/nfs/test/packages/RestBlockDriver# echo "http://192.168.0.5/test" > /sys/class/dewb/add_mirrors
bash: echo: write error: Invalid argument
root@app05:/nfs/test/packages/RestBlockDriver# echo "http://192.168.0.5/test" > /sys/class/dewb/add_mirrors
root@app05:/nfs/test/packages/RestBlockDriver# cat /sys/class/dewb/mirrors
http://192.168.0.5/test

we can cat  /sys/class/dewb/mirrors safely but before that, we need to echo twice. 
###### 
###### 

---

root@app05:/nfs/test/packages/RestBlockDriver# rmmod dewblock
root@app05:/nfs/test/packages/RestBlockDriver# ls
dewb.c       dewb.h       dewblock.ko     dewblock.o          dewb.o        fio_amazon_dewblock.sh  modules.order   test.sh
dewb_cdmi.c  dewb_http.c  dewblock.mod.c  dewblock_parted.sh  dewb_sysfs.c  jsmn                    Module.symvers  udev
dewb_cdmi.o  dewb_http.o  dewblock.mod.o  dewblock.sh         dewb_sysfs.o  Makefile                README.md
root@app05:/nfs/test/packages/RestBlockDriver# insmod dewblock.ko
root@app05:/nfs/test/packages/RestBlockDriver# lsmod | grep dewblock
dewblock            136511423  0
root@app05:/nfs/test/packages/RestBlockDriver# sudo -s
root@app05:/nfs/test/packages/RestBlockDriver# echo "http://192.168.0.5/test" > /sys/class/dewb/add_mirrors
bash: echo: write error: Invalid argument
root@app05:/nfs/test/packages/RestBlockDriver# echo "http://192.168.0.5/test" > /sys/class/dewb/add_mirrors
root@app05:/nfs/test/packages/RestBlockDriver# cat /sys/class/dewb/mirrors
http://192.168.0.5/test
root@app05:/nfs/test/packages/RestBlockDriver# curl http://192.168.0.5
<html><body><h1>Index of /</h1>
<a href="../">../</a><br><a href="README">README</a><br><a href="sys/">sys/</a><br><a href="test/">test/</a><br></body></html>root@app05:/nfs/test/packages/RestBlockDriver# curl http://192.168.0.5/test
root@app05:/nfs/test/packages/RestBlockDriver# for i in {1..16}; do echo "vol$i 8000000000" > /sys/class/dewb/create; done
root@app05:/nfs/test/packages/RestBlockDriver# parted -l | grep dewb
Error: /dev/dewba: unrecognised disk label
Error: /dev/dewbb: unrecognised disk label
Error: /dev/dewbc: unrecognised disk label
Error: /dev/dewbd: unrecognised disk label
Error: /dev/dewbe: unrecognised disk label
Error: /dev/dewbf: unrecognised disk label
Error: /dev/dewbg: unrecognised disk label
Error: /dev/dewbh: unrecognised disk label
Error: /dev/dewbi: unrecognised disk label
Error: /dev/dewbj: unrecognised disk label
Error: /dev/dewbk: unrecognised disk label
Error: /dev/dewbl: unrecognised disk label
Error: /dev/dewbm: unrecognised disk label
Error: /dev/dewbn: unrecognised disk label
Error: /dev/dewbo: unrecognised disk label
Error: /dev/dewbp: unrecognised disk label

root@app05:/nfs/test/packages/RestBlockDriver# for i in {1..16}; do echo "Running dewblock $i"; parted /dev/dewb/vol$i/device --script -- mklabel gpt; parted /dev/dewb/vol$i/device --script -- mkpart primary 1 -1; parted /dev/dewb/vol$i/device --script print; kpartx -s -a /dev/dewb/vol$i/part-1; done

.....

root@app05:/nfs/test/packages/RestBlockDriver# parted -l | grep dewb
Disk /dev/dewba: 8000MB
Disk /dev/dewbb: 8000MB
Disk /dev/dewbc: 8000MB
Disk /dev/dewbd: 8000MB
Disk /dev/dewbe: 8000MB
Disk /dev/dewbf: 8000MB
Disk /dev/dewbg: 8000MB
Disk /dev/dewbh: 8000MB
Disk /dev/dewbi: 8000MB
Disk /dev/dewbj: 8000MB
Disk /dev/dewbk: 8000MB
Disk /dev/dewbl: 8000MB
Disk /dev/dewbm: 8000MB
Disk /dev/dewbn: 8000MB
Disk /dev/dewbo: 8000MB
Disk /dev/dewbp: 8000MB

root@app05:/nfs/test/packages/RestBlockDriver# for i in {1..16}; do ls -l /dev/dewb/vol$i/device; done
lrwxrwxrwx 1 root root 11 Aug  7 00:35 /dev/dewb/vol1/device -> ../../dewba
lrwxrwxrwx 1 root root 11 Aug  7 00:35 /dev/dewb/vol2/device -> ../../dewbb
lrwxrwxrwx 1 root root 11 Aug  7 00:35 /dev/dewb/vol3/device -> ../../dewbc
lrwxrwxrwx 1 root root 11 Aug  7 00:35 /dev/dewb/vol4/device -> ../../dewbd
lrwxrwxrwx 1 root root 11 Aug  7 00:35 /dev/dewb/vol5/device -> ../../dewbe
lrwxrwxrwx 1 root root 11 Aug  7 00:35 /dev/dewb/vol6/device -> ../../dewbf
lrwxrwxrwx 1 root root 11 Aug  7 00:35 /dev/dewb/vol7/device -> ../../dewbg
lrwxrwxrwx 1 root root 11 Aug  7 00:35 /dev/dewb/vol8/device -> ../../dewbh
lrwxrwxrwx 1 root root 11 Aug  7 00:35 /dev/dewb/vol9/device -> ../../dewbi
lrwxrwxrwx 1 root root 11 Aug  7 00:35 /dev/dewb/vol10/device -> ../../dewbj
lrwxrwxrwx 1 root root 11 Aug  7 00:35 /dev/dewb/vol11/device -> ../../dewbk
lrwxrwxrwx 1 root root 11 Aug  7 00:35 /dev/dewb/vol12/device -> ../../dewbl
lrwxrwxrwx 1 root root 11 Aug  7 00:35 /dev/dewb/vol13/device -> ../../dewbm
lrwxrwxrwx 1 root root 11 Aug  7 00:35 /dev/dewb/vol14/device -> ../../dewbn
lrwxrwxrwx 1 root root 11 Aug  7 00:35 /dev/dewb/vol15/device -> ../../dewbo
lrwxrwxrwx 1 root root 11 Aug  7 00:35 /dev/dewb/vol16/device -> ../../dewbp

root@app05:/nfs/test/packages/RestBlockDriver# curl http://192.168.0.5/test/
<html><body><h1>Index of /test</h1>
<a href="../">../</a><br><a href="vol10">vol10</a><br><a href="vol16">vol16</a><br><a href="vol4">vol4</a><br><a href="vol5">vol5</a><br><a href="vol9">vol9</a><br><a href="vol14">vol14</a><br><a href="vol13">vol13</a><br><a href="vol2">vol2</a><br><a href="vol6">vol6</a><br><a href="vol7">vol7</a><br><a href="vol8">vol8</a><br><a href="vol11">vol11</a><br><a href="vol1">vol1</a><br><a href="vol3">vol3</a><br><a href="vol12">vol12</a><br><a href="vol15">vol15</a><br></body></html>root@app05:/nfs/test/packages/RestBlockDriver#

**Comment by AlbertoRu11** [comment]
Why am i getting this?
echo: write error: Invalid argument
